name: CI

on:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.8

      - name: Linting
        run: |
          pip install nox
          nox -s check-trailing-whitespaces
